### ISSUE TITLE
Query malformed in Neptune

### ISSUE THREAD

**Issue by roddolf** [CarbonLDP/sparqler#59]
Amazon Neptune throws an error for queries with prefixes because currently, we print prefixes declaration using a space between the colon and the IRI declaration.
```sparql
PREFIX ex:  <https://example.com>
```

RDF4J, GraphDB, and Stardog don't throw a problem in queries with space or without it, so we can remove the printing of this space.
```sparql
PREFIX ex:<https://example.com>
```

**Comment by mhernandeza** [comment]
Closing the issue since Neptune does accept both notations for SPARQL prefixes.
